export { ApiClient } from './client';
export type { ApiClientConfig, ApiTransport, QueryValue, RequestOptions, RetryEvent } from './client';

export {
  ApiRequestError,
  clientErrorCodes,
  decodeApiError,
  errorStatus,
  isApiRequestError,
  isRetryableErrorCode,
  isRetryableStatus,
  isServerErrorCode,
  serverErrorCodes,
  statusForErrorCode,
  timeoutError,
  toApiRequestError,
} from './errors';
export type { ApiErrorCode, ClientErrorCode, ServerErrorCode } from './errors';

export {
  assertIdempotencyKey,
  createIdempotencyKey,
  defaultRetryPolicy,
  defaultSleep,
  defaultTimeoutMs,
  idempotencyKeyMaxLength,
  idempotencyKeyMinLength,
  isIdempotentMethod,
  isSafeMethod,
  isValidIdempotencyKey,
  methodOf,
  retryDelayMs,
  shouldRetry,
} from './policy';
export type { RetryContext, RetryDecision, RetryPolicy, Sleep } from './policy';

export {
  clampLimit,
  collectPages,
  CursorStore,
  decodePage,
  defaultPageLimit,
  hasMore,
  maxPageLimit,
  nextPagination,
  paginationQuery,
} from './pagination';
export type { CollectOptions, Page, PageFetcher } from './pagination';

export { createMemoryStorage, storageKeys } from './storage';
export type { StorageAdapter } from './storage';

export { createDeviceIdentity } from './device';
export type { DeviceIdentity } from './device';

export { createFetchTransport } from './transport';
export type { FetchLike, FetchTransportConfig } from './transport';

export {
  createAuthClient,
  createCashSessionsClient,
  createCatalogClient,
  createCustomersClient,
  createEcommerceClient,
  createInventoryClient,
  createLoyaltyClient,
  createOrdersClient,
  createOrganizationsClient,
  createPaymentsClient,
  createPharmacyApi,
  createPrescriptionsClient,
  createProductsClient,
  createPurchaseOrdersClient,
  createPurchasesClient,
  createReportsClient,
  createResourceClient,
  createSalesClient,
  createStorefrontClient,
  createStoresClient,
  createSuppliersClient,
  createSyncClient,
  createUsersClient,
} from './resources';
export type {
  AdoptPayload,
  AdoptResult,
  AuthClient,
  CashSession,
  CashSessionsClient,
  CashSessionStatus,
  AuthSession,
  CurrentOrganization,
  CurrentUser,
  Device,
  DeviceClaim,
  DeviceRegisterRequest,
  DeviceStatus,
  EcommerceClient,
  EcommerceListing,
  GuestCheckoutResult,
  ListingUpsertRequest,
  LogoutResult,
  MembershipOption,
  MembershipStore,
  OnlineFulfillment,
  OnlineOrder,
  OnlineOrderStatus,
  OrderCheckoutItem,
  OrderCreateRequest,
  OrderItemLine,
  OrderListFilters,
  OrderStatusHistoryEntry,
  OrderTransitionRequest,
  OrdersClient,
  OrganizationCreateRequest,
  OrganizationCreateResponse,
  OrganizationProfile,
  OrganizationSettings,
  OrganizationSettingsResponse,
  OrganizationSettingsUpdate,
  OrganizationUpdateRequest,
  OrganizationsClient,
  OtpChallenge,
  OtpPurpose,
  OtpRequest,
  OtpVerifyRequest,
  PharmacyApi,
  PinLoginRequest,
  PinSetRequest,
  PinStatus,
  Prescription,
  PrescriptionAttachRequest,
  PrescriptionCreateRequest,
  PrescriptionFileMeta,
  PrescriptionFileRequest,
  PrescriptionListFilters,
  PrescriptionReviewEntry,
  PrescriptionReviewRequest,
  PrescriptionStatusWire,
  PrescriptionsClient,
  PublicCatalogueItem,
  RefreshRequest,
  ResourceClient,
  SelectContextRequest,
  SessionListFilters,
  StaffRole,
  StoreAssignmentRequest,
  StoreCreateRequest,
  StoreOperatingStatus,
  StoreProfile,
  StoreSettings,
  StoreSettingsResponse,
  StoreSettingsUpdate,
  StoreStatusUpdateRequest,
  StoreUpdateRequest,
  Storefront,
  StorefrontClient,
  StorefrontUpsertRequest,
  StoresClient,
  TokenBundle,
  UserCreateRequest,
  UserListFilters,
  UserProfile,
  UserRoleUpdateRequest,
  UserStatusUpdateRequest,
  UserUpdateRequest,
  UsersClient,
} from './resources';
export type {
  CatalogAlternativeItem,
  CatalogAlternativesParams,
  CatalogClient,
  CatalogProductCreateRequest,
  CatalogProductRecord,
  CatalogReference,
  CatalogSearchItem,
  CatalogSearchParams,
  Customer,
  CustomerAddress,
  CustomerAddressCreateRequest,
  CustomerCreateRequest,
  CustomerFilters,
  CustomerHistorySummary,
  CustomerUpdateRequest,
  CustomersClient,
  DailyMetric,
  DiscountApproval,
  DiscountApprovalRequest,
  DiscountInput,
  LoyaltyAccount,
  LoyaltyClient,
  LoyaltyTransaction,
  LoyaltyTransactionRequest,
  DiscountMode,
  ExpiringBatch,
  ExpiryWarning,
  Expense,
  ExpenseCreateRequest,
  ExpenseFilters,
  InventoryClient,
  InventoryIntake,
  InventoryIntakeRequest,
  LowStockItem,
  AdjustmentRequest,
  BalanceSnapshot,
  ProductBatch,
  MovementQuery,
  MovementLedgerRow,
  RackSummary,
  RackRenameRequest,
  ReorderSuggestion,
  Stocktake,
  StocktakeCreateRequest,
  StocktakeFinalized,
  StocktakeLine,
  StocktakeLineRequest,
  StocktakeStatus,
  StockTransferStatus,
  StockTransferSummary,
  TransferCreateRequest,
  ValuationLine,
  InventoryValuation,
  DeadStockLine,
  DeadStockReport,
  CogsSummary,
  Payment,
  PaymentMethod,
  PaymentsClient,
  PaymentStatus,
  PharmacyProduct,
  PharmacyProductCreateRequest,
  ProductsClient,
  PoConvertResult,
  Purchase,
  PurchaseCreateRequest,
  PurchaseItem,
  PurchaseOrder,
  PurchaseOrderCreateRequest,
  PurchaseOrderItem,
  PurchaseOrderItemAddRequest,
  PurchaseOrderItemUpdateRequest,
  PurchaseOrderStatusWire,
  PurchaseOrdersClient,
  PurchasesClient,
  PurchaseStatus,
  ReceiveBatchRequest,
  ReportsClient,
  Sale,
  SaleChargeInput,
  SaleChannel,
  SaleCreateRequest,
  SaleItem,
  SaleListFilters,
  SalePaymentInput,
  SaleReturn,
  SaleReturnRequest,
  SalesClient,
  SaleStatus,
  ShelfItem,
  StockRow,
  StoreProduct,
  StoreProductEnableRequest,
  Supplier,
  SuppliersClient,
  SyncAck,
  SyncClient,
  SyncDevice,
  SyncEnvelope,
  SyncPullChange,
  TodayMetrics,
} from './resources';
